### ISSUE TITLE
E5108: Error executing lua [string ":lua"]:1: attempt to index global 'surround' (a nil value)

### ISSUE THREAD

**Issue by icanrelate** [blackCauldron7/surround.nvim#1]
I tried this plugin, I seem to get an error when I visually select and press `s<char>`.
the substitute - `s` is being overridden so it's definitely installed correctly.
ctrl-s seems to work only for `',"` but not on closing brackets like `]`

**Comment by blackCauldron7** [comment]
What error do you get? and do you mean when you press `<c-s>]` it doesn't insert opening character?
