### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by andreicorpo** [blackCauldron7/surround.nvim#10]
I just can't get it to work. Whenever I press `s` I get into insert mode.

[My config](https://github.com/andreicorpo/nvim)

My neovim version:
```
NVIM v0.5.0-dev+nightly-119-g76f5c7286
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by blackCauldron7** [comment]
I added a startup message in the latest commit.
Please update and tell if there is a message by doing :lua require"surround".setup{} in the command line mode.

**Comment by andreicorpo** [comment]
I do get a message saying `surround.nvim started successfully`

**Comment by blackCauldron7** [comment]
so did you get the message after running `:lua require"surround".setup{}` or automatically?

**Comment by andreicorpo** [comment]
Both. 🤔

**Comment by blackCauldron7** [comment]
Then probably some other plugin replaces the mappings please post the output of `:verbose nmap sr{[`

**Comment by andreicorpo** [comment]
`n    sr{[ * <Cmd>lua require'surround'.surround_replace("{", "[")<CR>`

**Comment by blackCauldron7** [comment]
Damn its clearly mapped and you aren't getting any errors, probably a bug with the current nightly or something.

**Comment by andreicorpo** [comment]
Maybe. Thanks for your support and this awesome plugin. 🙏🏼

**Comment by blackCauldron7** [comment]
Thank you for your kind words.
Does the mode change to insert immediately after you press `s` or after some delay because you have to press the key mappings in succession for surround.nvim to work, there is no waiting involved.

**Comment by andreicorpo** [comment]
It happens immediately.

**Comment by blackCauldron7** [comment]
Well you said this is an awesome plugin does that mean this was working for you before and stopped working recently?

**Comment by andreicorpo** [comment]
No. I like the idea. It is something I am missing since switching from vscode.

**Comment by blackCauldron7** [comment]
well there are some alternatives if you don't know https://github.com/tpope/vim-surround and https://github.com/machakann/vim-sandwich.

**Comment by andreicorpo** [comment]
I know. But this one is in lua. 😎

**Comment by blackCauldron7** [comment]
ah got it your timeout is very low

https://github.com/andreicorpo/nvim/blob/master/lua/settings.lua
line 34

**Comment by andreicorpo** [comment]
Oh my god. You are right!!! It is working now. Thanks a lot!

**Comment by blackCauldron7** [comment]
Glad you figured it out :)
