### ISSUE TITLE
example of setting different prefix key?

### ISSUE THREAD

**Issue by alok** [blackCauldron7/surround.nvim#11]
i'd like to use <c-s> instead of `s` since that's bound to something else

**Comment by blackCauldron7** [comment]
Just update the readme.md
tldr;
let g:surround_prefix = ...

**Comment by alok** [comment]
setting this doesn't seem to do anything, at least when i use packer since the plugin is loaded before the config is read.

do you have any suggestions on setting the variable before the plugin is loaded?

**Comment by blackCauldron7** [comment]
All you have to do is set the variable before calling surround.setup function

**Comment by alok** [comment]
i did

```
use {
            "blackCauldron7/surround.nvim",
            config = function()

                vim.g.surround_prefix = "<c-s>"
                vim.g.surround_load_autogroups = true

                require"surround".setup {}
            end,
        }
```

and it didn't work

**Comment by blackCauldron7** [comment]
Did you pull the latest commit with `:PackerUpdate`?

**Comment by alok** [comment]
yes

**Comment by blackCauldron7** [comment]
Weird that same config works for me are the mappings with the default prefix being set?

**Comment by alok** [comment]
yes, the mappings with `s` are set.

**Comment by blackCauldron7** [comment]
Did you run `:PackerCompile` after editing the config function?

If not try that.

**Comment by alok** [comment]
I did

**Comment by blackCauldron7** [comment]
Can you link your dotfiles.

**Comment by blackCauldron7** [comment]
Closed because of inactivity.

**Comment by CleoMenezes** [comment]
I can reproduce the same issue.
Basically, the new prefix works, but the 's' prefix is ​​still one of the shortcuts.

**Comment by LoveSponge** [comment]
I also can't get this to work... I'm trying to map 'S' (also tried '<S-S>' just in case - no dice.
Whenever I hit S, it carries the default vim action.
