### ISSUE TITLE
Error when repeating last surround command with ss and adding surroundings.

### ISSUE THREAD

**Issue by rafamadriz** [blackCauldron7/surround.nvim#12]
Repeating last surround command with `ss` doesn't work and gives the following error:
![2021-May- 8](https://user-images.githubusercontent.com/67771985/117540818-7d15c780-b000-11eb-978e-06f1cf3e43e5.png)

Also, I have another question: If I understand correctly adding surroundings is just `s<char>` right ? That doesn't work for me. 

Example:

adding surround on `test` with `s"`

```
# behavior
t"st

# expected behavior
"test"
```

The other options are working fine for me, like replacing and deleting. My problem is with the two options above.

**Comment by blackCauldron7** [comment]
Adding surroundings needs visual selection or `ys` then a motion and character.

**Comment by blackCauldron7** [comment]
Closed because of inactivity.

**Comment by gbrlsnchs** [comment]
The issue with `ss` still persists though. My example is, I run `sr"'` and then `ss`, and it throws:
```
E5108: Error executing lua ...site/pack/paqs/start/surround.nvim/lua/surround/init.lua:749: Vim(lua):E5108: Error executing lua ...site/pack/paqs/start/surround.nvim/lua/surround/ini
t.lua:574: attempt to index local 'char_2_pairs' (a nil value)
```

**Comment by blackCauldron7** [comment]
latest commit fixes this
