### ISSUE TITLE
Feature request: Highlight selection before operation

### ISSUE THREAD

**Issue by konapun** [blackCauldron7/surround.nvim#13]
When using vim-sandwich I can make a selection, e.g. `ysi{` to select everything in a block and the match would be highlighted before applying the next surround operation. I enjoyed this feature because at times I was indented further than I expected and was able to catch it before adding a surrounding and would love to have that same feature in surround.nvim.

**Comment by blackCauldron7** [comment]
you want the selection to be highlighted?

**Comment by konapun** [comment]
Yeah, here's an example of executing `ysa{` with sandwich. When I tried surround it didn't show the actual selection.

<img width="515" alt="Screen Shot 2021-08-03 at 5 39 49 PM" src="https://user-images.githubusercontent.com/498643/128095427-1d5f25bb-c235-464c-ac90-ffd49f743d1b.png">

**Comment by augustocdias** [comment]
@blackCauldron7 this is the function you're looking for

```lua
--- Highlight range between two positions
---
---@param bufnr number of buffer to apply highlighting to
---@param ns namespace to add highlight to
---@param higroup highlight group to use for highlighting
---@param rtype type of range (:help setreg, default charwise)
---@param inclusive boolean indicating whether the range is end-inclusive (default false)
require'vim.highlight'.range(bufnr, ns, higroup, start, finish, rtype, inclusive)
```
