### ISSUE TITLE
`ds` doesn't work in 'surround' mode

### ISSUE THREAD

**Issue by meriops** [blackCauldron7/surround.nvim#17]
In 'surround' mode, whenever I try `ds`, I get E5108: Error executing lua .../pack/packer/start/surround.nvim/lua/surround/parser.lua:235: attempt to perform arithmetic on local 'requested_pair' (a nil value). In sandwich mode, `sd` works ok. Is that just me doing something wrong, or?

**Comment by blackCauldron7** [comment]
should be fixed

**Comment by meriops** [comment]
Indeed! Thanks!
