### ISSUE TITLE
Not integrate well with nvim-treesitter/nvim-treesitter-textobjects

### ISSUE THREAD

**Issue by glyh** [blackCauldron7/surround.nvim#18]
Here's the [plugin](https://github.com/nvim-treesitter/nvim-treesitter-textobjects)
I've tried to append a surround on a function, but it won't work:
```lua
  use {"itchyny/lightline.vim",
    config = function()
      nvim.g.lightline = {colorscheme = "iceberg"}
    end
  }
```
- Reproduce: 
  1. put cursor inside the function.
  2. press "ysaf("

- Expect Result: the function is surrounded
- Actual Result: something wired is surround

- Some suggestions: 
  Mapping operators, then emulate visual mode to get the textobjects' border, [here](https://learnvimscriptthehardway.stevelosh.com/chapters/34.html) for example. 
  This is the approach in vim-surround. 
  This might seem ugly and primitive, but it will provide compatibility with any kind of text object plugins, as long as they support commands such as `v`, `d` (primitive vim commands)

**Comment by blackCauldron7** [comment]
Should be fixed now

**Comment by glyh** [comment]
Thanks a lot!
