### ISSUE TITLE
Support for sa mapping from vim-sandwich

### ISSUE THREAD

**Issue by gotgenes** [blackCauldron7/surround.nvim#19]
surround.nvim has [sandwich mode mappings](https://github.com/blackCauldron7/surround.nvim#normal-mode---sandwich-mode). My best guess is this is in reference to [vim-sandwich](https://github.com/machakann/vim-sandwich). I noticed that vim-sandwich uses `sa{motion/textobject}{addition}` [for addition of surrounding characters](https://github.com/machakann/vim-sandwich#add).

> For example, a key sequence `saiw(` makes **foo** to **(foo)**.

I don't see this mapping mentioned in the docs. Is it supported, and if not, are there plans to support it?

Thanks.

**Comment by blackCauldron7** [comment]
Done try the latest commit and please close the issue if it fixes things.

**Comment by ner0-m** [comment]
I've tried this and it seems to work nicely, expect that it does not respect custom prefixes. Would it be possible to fix that. That would be awesome!

**Comment by blackCauldron7** [comment]
fixed iirc

**Comment by ner0-m** [comment]
Thanks! Works for me
