### ISSUE TITLE
Errors on last updates

### ISSUE THREAD

**Issue by augustocdias** [blackCauldron7/surround.nvim#28]
I'm having some errors since the last updates (I don't know which commit triggered it because I was away for some time and there many new commits).

```
E15: Invalid expression: <80><fd>hset operatorfunc=SurroundAddOperatorMode^Mg@
E15: Invalid expression: <80><fd>hlua require'surround'.surround_delete()^M
```

Looking through the README I didn't find anything that I should change in my config...

Here's my config:

```lua
require('surround').setup({
    brackets = { '(', '{', '[', '<' },
    pairs = {
        nestable = { { '(', ')' }, { '{', '}' }, { '[', ']' }, { '<', '>' } },
        linear = { { '"', '"' }, { "'", "'" }, { 'r#"', '"#' } }
    },
    mappings_style = 'sandwich',
    surround_map_insert_mode = false
})
```

**Comment by gbprod** [comment]
Same here using surround mapping:
 
    require("surround").setup({
      mappings_style = "surround",
    })

**Comment by blackCauldron7** [comment]
reverted latest commit try now and close if it fixes it please.

**Comment by augustocdias** [comment]
Worked.
