### ISSUE TITLE
'ss' does not seems to work

### ISSUE THREAD

**Issue by VKondakoff** [blackCauldron7/surround.nvim#29]
From the docs: `ss repeats last surround command.`
Pressing `saiw'` surrounds current word with `'`, but when I move to the next word and press `ss` just nothing happens.

**Comment by blackCauldron7** [comment]
ss mapping is not intended to be used with surround add

**Comment by blackCauldron7** [comment]
Its really difficult to store the last context ie word, paragraph etc.. so it's not supported

**Comment by VKondakoff** [comment]
So, which commands does 'ss' support? How to use it?

**Comment by blackCauldron7** [comment]
everything else pretty much

**Comment by blackCauldron7** [comment]
delete, replace afaik

**Comment by VKondakoff** [comment]
Thanks, pretty sure this should be mentioned in the docs.
Closing now.

**Comment by blackCauldron7** [comment]
updated README thanks for the feedback
