### ISSUE TITLE
'<c-s><char><c-s>' does not seems to work

### ISSUE THREAD

**Issue by VKondakoff** [blackCauldron7/surround.nvim#30]
From the docs: `<c-s><char><c-s> will insert both pairs on newlines insert mode.`
Pressing `Ctrl-s'Ctrl-s` in Insert mode inserts this: `'^S'`.

**Comment by blackCauldron7** [comment]
I cannot reproduce this issue.

**Comment by VKondakoff** [comment]
Yes, sorry, false alarm: I should possible increase the 'timeoutlen' option.
Closing the issue.
