### ISSUE TITLE
Feature request or I'm missing something? - Surround word under cursor in NORMAL without entering VISUAL

### ISSUE THREAD

**Issue by TobiasDev** [blackCauldron7/surround.nvim#32]
I'd to have a quick way of surrounding a word without going into VISUAL mode. Right now in the "surround" setting you need to visually select the word and then pressing s" to make it surround. It would be cool if it would be possible to do this without first entering visual mode for single words you want to update.

**Comment by blackCauldron7** [comment]
try `ysiw`

**Comment by TobiasDev** [comment]
Wow, I missed that! Thank you! That is exactly what I was looking for. :)
