### ISSUE TITLE
Feature Request: The key to space is different from vim-surround

### ISSUE THREAD

**Issue by rytkmt** [blackCauldron7/surround.nvim#33]
thank you for the plugin.

The key to space is different from vim-surround.

https://github.com/tpope/vim-surround#surroundvim

![image](https://user-images.githubusercontent.com/21115950/146167462-1bc9e232-4085-4f33-8d5c-829b211a5ca4.png)

lua/surround/init.lua L180-L183
```lua
	local space = ""
	if table.contains(vim.tbl_flatten(surround_pairs.nestable), char) and char == char_pairs[CLOSING] then
		space = " "
	end
```

I want to choice opening key or closing key for add space.

I'm not good at English. sorry.

**Comment by blackCauldron7** [comment]
its the other way round in this plugin right?

**Comment by rytkmt** [comment]
yes. In this plugin, the key is reversed, so I make a mistake. :(

I want to choice the key.

**Comment by blackCauldron7** [comment]
Done the opening char is the default one to add space now and there is a new option
`space_on_closing_char: true / false`

**Comment by blackCauldron7** [comment]
Close this issue if this fixes it

**Comment by rytkmt** [comment]
checked that it has been fixed. thank you very much.
