### ISSUE TITLE
Add tag symbols {"<" , ">"} as part of the default nestable pairs

### ISSUE THREAD

**Issue by ricglz** [blackCauldron7/surround.nvim#34]
Hey!
Nice work you have done, I have a question, is it possible to add the tag symbols {"<" , ">"} as part of the default nestable pairs? Is not that I don't know that I can or how to add it, but instead I think is something other developers doing html/jsx may use. If you have an argument against it, it's ok, I'm just curious which it is?
Thanks

**Comment by blackCauldron7** [comment]
makes sense I don't know why I didn't think of it sooner. done added in latest commit.

Please close the issue if the latest commit fixes your issue
