### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by melsiir** [blackCauldron7/surround.nvim#36]
How I can add tags it seem like it doesn't work with tags

**Comment by blackCauldron7** [comment]
what is tags?

**Comment by melsiir** [comment]
> what is tags?

Like I want to surround my text with <p> or <li> or <em>

**Comment by blackCauldron7** [comment]
I literally see a blank space after "with".

**Comment by melsiir** [comment]
> I literally see a blank space after "with".

I don't know what happens but the tags I deleted some whow but what I mean for example p tags or em tag or any html tags

**Comment by blackCauldron7** [comment]
html tags are not supported its even written in the README

**Comment by melsiir** [comment]
> html tags are not supported its even written in the README
IS there are any intentions for support ?

**Comment by blackCauldron7** [comment]
Yeah but not in the mear future. I don't have enough time right now to implement it. If someone is up for it. I would be happy to review a PR.
