### ISSUE TITLE
E117: Unknown function: SurroundAddOperatorMode

### ISSUE THREAD

**Issue by nyngwang** [blackCauldron7/surround.nvim#40]
I got this error and the plugin doesn't work at all now.

**Comment by Daxtorim** [comment]
I guess you use `mappings_style = "surround"`, right? So `ys` is what's broken?

In the last update I only changed the `sandwich` mapping and totally forgot to change the `surround` mapping to the new one.

Sorry about that. 😞 (linked PR will fix it)

**Comment by nyngwang** [comment]
Hi, thanks for your quick fix. No worries, wish you a good day 😸  @Daxtorim
