### ISSUE TITLE
add option to disable selection mode mappings

### ISSUE THREAD

**Issue by max397574** [blackCauldron7/surround.nvim#44]
It rly annoys me that this plugin creates mappings for selection mode.
When I use plugins with placeholders and wanna write sth with `s`it won't work

**Comment by max397574** [comment]
This should be as simple as adding something like
```lua
if settings.map_select_mode then ... end
````
here: https://github.com/blackCauldron7/surround.nvim/blob/b0105011437ab148261b5c4ed6b84c735c54cd61/lua/surround/init.lua#L595

**Comment by max397574** [comment]
if you want I can open a pr for it

**Comment by Daxtorim** [comment]
Are you actually bothered by the mapping in `VISUAL` mode? Or is it just `SELECT` mode?

If it is just `SELECT` mode that is bothersome, creating the mapping only for `VISUAL` mode would be easier/preferable:
(replaced the `v` by `x`)
```lua
map("x", "s", "<esc>gv<cmd>lua require'surround'.surround_add()<cr>") 
```

To be honest I didn't even understand what `SELECT` mode really did until I just saw how LuaSnip used it.
