### ISSUE TITLE
Don't press Enter when using `cs<><>`

### ISSUE THREAD

**Issue by petobens** [blackCauldron7/surround.nvim#46]
I've recently noticed that if want, for instance, to change from single to double quotes and press `cs'"` I get:
```
(Surround) Character: '
(Surround) Character: "
Press ENTER or type command to continue
```
How can I avoid pressing `Enter`?

**Comment by Daxtorim** [comment]
Put `set cmdheight=2` in your .vimrc. That will increase the box for command output at the bottom of the screen to 2 lines, creating enough space for all the output without prompting you for input to dismiss it.

**Comment by petobens** [comment]
@Daxtorim can you disable the message altogether and simply wait for the user input? I like having my cmdheight set to 1.

**Comment by Daxtorim** [comment]
Done in #47

You can now pass `prompt = false` to `setup()` to disable the input prompt entirely.

**Comment by petobens** [comment]
Thank you!
