### ISSUE TITLE
The key "s" doesn't surround 

### ISSUE THREAD

**Issue by EpsilonKu** [blackCauldron7/surround.nvim#5]
So I installed plugin with vim-plug with Neovim version: 0.5.0-dev with 20.11 build. And it doesn't work. 

NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by blackCauldron7** [comment]
You sure the plugin is loaded? Read the readme you need to use a function to setup the plugin.

**Comment by EpsilonKu** [comment]
Yes, I loaded it. with lua require"surround".setup{}

**Comment by EpsilonKu** [comment]
The problem is when I press s at visual mod it remove whole line and switch to insert mode.

**Comment by blackCauldron7** [comment]
Its really difficult to debug cause i don't really know what could cause this as there are no error messages too. Maybe if you'd send the startup log.

**Comment by blackCauldron7** [comment]
Please change the title of the issue to the real problem please you should have opened with that i thought it wasn't loading.

**Comment by EpsilonKu** [comment]
[myVim.log](https://github.com/blackCauldron7/surround.nvim/files/5751401/myVim.log)
So "vim -V9myVim.log" command doesn't show lua file loading.

**Comment by EpsilonKu** [comment]
IDK, but it works. So I close this issue, thanks.
