### ISSUE TITLE
Suggestion: Move plugin files to lua/surround/*

### ISSUE THREAD

**Issue by Joakker** [blackCauldron7/surround.nvim#7]
Since the parser and util files are in the root of the lua scripts, they might clash with similarly named files in the user's config directory.

The plugin could still be activated by `require'surround'.setup{}` by renaming `surround.lua` to `surround/init.lua`, and then the file does `require'surround.util` instead of just `require'util'`

If necessary, I can make a pull request 😃

**Comment by blackCauldron7** [comment]
My exams are going i am really busy it'll be appreciated if you could make that pull request and thanks for the feedback.

**Comment by Joakker** [comment]
gotcha
